# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(901, 701)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setStyleSheet("\n"
"QMainWindow {\n"
"    background-image: url(:/img/icons-white/login.png);\n"
"        background-image: url(:/img/icons-white/login.png);\n"
"\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border:none;\n"
"    border-bottom: 2px solid#28a2a2;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: #153947;\n"
"    border: 2px solid  #fff;\n"
"    border-radius: 5px;\n"
"    padding: 6px\n"
"}\n"
"\n"
"QPushButton:hover\n"
"QPushButton:clicked{\n"
"background-color  #0b5ed7;\n"
"border: 2px solid #9ac3fe;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setStyleSheet("        background-image: url(:/img/icons-white/login.png);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setVerticalSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(self.widget_2)
        self.widget.setMinimumSize(QtCore.QSize(300, 200))
        self.widget.setStyleSheet(" color:#bfdbd7;")
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.labelWelcome = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.labelWelcome.setFont(font)
        self.labelWelcome.setAlignment(QtCore.Qt.AlignCenter)
        self.labelWelcome.setObjectName("labelWelcome")
        self.gridLayout_3.addWidget(self.labelWelcome, 0, 0, 1, 1)
        self.labelUser = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelUser.setFont(font)
        self.labelUser.setObjectName("labelUser")
        self.gridLayout_3.addWidget(self.labelUser, 1, 0, 1, 1)
        self.lineUser = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.lineUser.setFont(font)
        self.lineUser.setStyleSheet("")
        self.lineUser.setObjectName("lineUser")
        self.gridLayout_3.addWidget(self.lineUser, 2, 0, 1, 1)
        self.labelPsw = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelPsw.setFont(font)
        self.labelPsw.setObjectName("labelPsw")
        self.gridLayout_3.addWidget(self.labelPsw, 3, 0, 1, 1)
        self.linePsw = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.linePsw.setFont(font)
        self.linePsw.setStyleSheet("")
        self.linePsw.setObjectName("linePsw")
        self.gridLayout_3.addWidget(self.linePsw, 4, 0, 1, 1)
        self.loginButton = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.gridLayout_3.addWidget(self.loginButton, 5, 0, 1, 1)
        self.gridLayout.addWidget(self.widget, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/whiteIcons/icons-white/logo.svg"))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.widget_2, 1, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(228, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(227, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setMaximumSize(QtCore.QSize(181, 16777215))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/whiteIcons/icons-white/Group 452.png"))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 147, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 146, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem6, 2, 1, 1, 1)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        self.labelWelcome.setText(_translate("Form", "Welcome"))
        self.labelUser.setText(_translate("Form", "Username"))
        self.labelPsw.setText(_translate("Form", "Password"))
        self.loginButton.setText(_translate("Form", "Login"))
